name: deploy

on:
  repository_dispatch:
    types: [trigger-reploy]

jobs:
  run-b:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release = ${{ toJson(github.event.client_payload.github) }}"
