name: workflow b

on:
  repository_dispatch:
    types: [trigger-workflow-b]

jobs:
  run-b:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release = ${{ github.event.client_payload.release }}"
